# Generated by Django 3.1.7 on 2021-05-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1),
        ),
    ]
